require('./tk_env')
require('./web')

debugger


// (function() {
//     let originalFetch = window.fetch;

//     Object.defineProperty(window, 'fetch', {
//         get() {
//             return originalFetch;
//         },
//         set(value) {
//             console.warn('fetch 被篡改！');
//             debugger;
//             originalFetch = value;
//         },
//         configurable: true
//     });
// })();


const initobj = {
    "aid": 1988,
    "dfp": false,
    "boe": false,
    "intercept": true,
    "enablePathList": [
        "/node/share/",
        "/share/item/list",
        "/discover/render/undefined",
        "/share/item/explore/list",
        "/api/comment/list/",
        "/api/comment/list/reply/",
        "/api/commit/follow/user/",
        "/api/commit/item/digg/",
        "/aweme/v1/upload/image2/",
        "/api/notice/multi/",
        "/api/notice/count/",
        "/api/notice/digg/list/",
        "/api/user/following/request/list/",
        "/api/commit/follow/request/approve/",
        "/api/commit/follow/request/reject/",
        "/api/comment/digg/",
        "/api/comment/publish/",
        "/api/comment/delete/",
        "/api/sticker/item_list/",
        "/api/user/contact/list/",
        "/api/at/default/list/",
        "/api/comment/search/user/",
        "/web/aweme/v1/search/challengesug",
        "/web/aweme/v1/discover/search/",
        "/api/v1/item/create/",
        "/api/ba/business/suite/permission/list",
        "/api/search/user/full/",
        "/api/search/user/preview/",
        "/api/search/item/full/",
        "/api/search/general/full/",
        "/api/music/detail/",
        "/api/challenge/detail/",
        "/api/user/detail/",
        "/api/user/list/",
        "/api/item/detail/",
        "/api/question/detail/",
        "/api/question/item_list/",
        "/api/discover/challenge/",
        "/api/discover/user/",
        "/api/discover/music/",
        "/api/challenge/item_list/",
        "/api/music/item_list/",
        "/api/post/item_list/",
        "/api/favorite/item_list/",
        "/api/following/item_list/",
        "/api/recommend/item_list/",
        "/api/recommend/user/",
        "/api/recommend/embed_videos/",
        "/api/live/detail/",
        "/api/im/multi_user/",
        "/api/user/get/animation/",
        "/api/user/settings/",
        "/aweme/v1/music/list/",
        "/aweme/v1/adult/verify/get/accepted/id/types/",
        "/api/mix/detail",
        "/api/mix/item_list",
        "/api/uniqueid/check/",
        "/api/user/playlist/",
        "/api/reflow/item/detail/",
        "/api/reflow/user/detail/",
        "/api/reflow/recommend/item_list/",
        "/api/reflow/challenge/item_list/",
        "/api/reflow/post/item_list/",
        "/api/reflow/sticker/item_list/",
        "/api/reflow/playlist/item_list/",
        "/api/reflow/survey/detail/",
        "/api/reflow/repost/item_list/",
        "/api/impression/write/",
        "/api/user/set/animation/",
        "/api/aweme/set/react_duet_stitch/",
        "/api/aweme/modify/visibility/",
        "/api/aweme/delete/",
        "/api/schedule/aweme/delete/",
        "/passport/web/login_name/update/",
        "/api/update/profile/",
        "/api/commit/follow/request/approve/",
        "/api/commit/follow/request/reject/",
        "/api/commit/follow/user/",
        "/tiktok/v1/username/save_async/",
        "/api/ba/business/suite/account/off",
        "/api/ba/business/suite/account/quitcheck",
        "/api/playlist/create_with_items/",
        "/api/playlist/update/",
        "/api/playlist/modify_items/",
        "/api/item/collect",
        "/node/report/reasons",
        "/aweme/v1/aweme/feedback/",
        "/aweme/v2/aweme/feedback/",
        "/webcast.*",
        "/v1/message/send",
        "/v2/conversation/create",
        "/v1/voip/call",
        "/v1/conversation/add_participants",
        "/1/conversation/remove_participants",
        "/v1/conversation/update_participant",
        "/v1/conversation/set_setting_info",
        "/v1/conversation/get_setting_info",
        "/v1/conversation/upsert_core_ext_info",
        "/v1/conversation/upsert_settings_ext",
        "/v1/conversation/dissolve",
        "/v1/message/mark",
        "/v1/message/batch_unmark",
        "/v1/message/set_property",
        "/api-live/event/list",
        "/api-live/event/related-videos",
        "/api-live/event/detail",
        "/api-live/share/live",
        "/api-live/user/room",
        "/node-a/send/download_link",
        "/api/uniqueid/check/",
        "/api/v3/register/user/info/sync/",
        "/api/policy/notice/approve/",
        "/api/private_banner/ack/",
        "/api/privacy/agreement/record/agree/v1",
        "/api/v3/register/verification/age/",
        "/api/register/check/login/name/",
        "/api/user/detail/self/",
        "/passport/web/",
        "/shorten/",
        "/api/seo/kap/product_list/",
        "/bi/notification/reporter/record"
    ],
    "region": "sg-tiktok",
    "mode": 516,
    "isSDK": false
}

window.byted_acrawler.init(initobj)

const thisobj = {
    "options": {
        "aid": 1988,
        "isSDK": false,
        "enablePathList": [
            "/node/share/",
            "/share/item/list",
            "/discover/render/undefined",
            "/share/item/explore/list",
            "/api/comment/list/",
            "/api/comment/list/reply/",
            "/api/commit/follow/user/",
            "/api/commit/item/digg/",
            "/aweme/v1/upload/image2/",
            "/api/notice/multi/",
            "/api/notice/count/",
            "/api/notice/digg/list/",
            "/api/user/following/request/list/",
            "/api/commit/follow/request/approve/",
            "/api/commit/follow/request/reject/",
            "/api/comment/digg/",
            "/api/comment/publish/",
            "/api/comment/delete/",
            "/api/sticker/item_list/",
            "/api/user/contact/list/",
            "/api/at/default/list/",
            "/api/comment/search/user/",
            "/web/aweme/v1/search/challengesug",
            "/web/aweme/v1/discover/search/",
            "/api/v1/item/create/",
            "/api/ba/business/suite/permission/list",
            "/api/search/user/full/",
            "/api/search/user/preview/",
            "/api/search/item/full/",
            "/api/search/general/full/",
            "/api/music/detail/",
            "/api/challenge/detail/",
            "/api/user/detail/",
            "/api/user/list/",
            "/api/item/detail/",
            "/api/question/detail/",
            "/api/question/item_list/",
            "/api/discover/challenge/",
            "/api/discover/user/",
            "/api/discover/music/",
            "/api/challenge/item_list/",
            "/api/music/item_list/",
            "/api/post/item_list/",
            "/api/favorite/item_list/",
            "/api/following/item_list/",
            "/api/recommend/item_list/",
            "/api/recommend/user/",
            "/api/recommend/embed_videos/",
            "/api/live/detail/",
            "/api/im/multi_user/",
            "/api/user/get/animation/",
            "/api/user/settings/",
            "/aweme/v1/music/list/",
            "/aweme/v1/adult/verify/get/accepted/id/types/",
            "/api/mix/detail",
            "/api/mix/item_list",
            "/api/uniqueid/check/",
            "/api/user/playlist/",
            "/api/reflow/item/detail/",
            "/api/reflow/user/detail/",
            "/api/reflow/recommend/item_list/",
            "/api/reflow/challenge/item_list/",
            "/api/reflow/post/item_list/",
            "/api/reflow/sticker/item_list/",
            "/api/reflow/playlist/item_list/",
            "/api/reflow/survey/detail/",
            "/api/reflow/repost/item_list/",
            "/api/impression/write/",
            "/api/user/set/animation/",
            "/api/aweme/set/react_duet_stitch/",
            "/api/aweme/modify/visibility/",
            "/api/aweme/delete/",
            "/api/schedule/aweme/delete/",
            "/passport/web/login_name/update/",
            "/api/update/profile/",
            "/api/commit/follow/request/approve/",
            "/api/commit/follow/request/reject/",
            "/api/commit/follow/user/",
            "/tiktok/v1/username/save_async/",
            "/api/ba/business/suite/account/off",
            "/api/ba/business/suite/account/quitcheck",
            "/api/playlist/create_with_items/",
            "/api/playlist/update/",
            "/api/playlist/modify_items/",
            "/api/item/collect",
            "/node/report/reasons",
            "/aweme/v1/aweme/feedback/",
            "/aweme/v2/aweme/feedback/",
            "/webcast.*",
            "/v1/message/send",
            "/v2/conversation/create",
            "/v1/voip/call",
            "/v1/conversation/add_participants",
            "/1/conversation/remove_participants",
            "/v1/conversation/update_participant",
            "/v1/conversation/set_setting_info",
            "/v1/conversation/get_setting_info",
            "/v1/conversation/upsert_core_ext_info",
            "/v1/conversation/upsert_settings_ext",
            "/v1/conversation/dissolve",
            "/v1/message/mark",
            "/v1/message/batch_unmark",
            "/v1/message/set_property",
            "/api-live/event/list",
            "/api-live/event/related-videos",
            "/api-live/event/detail",
            "/api-live/share/live",
            "/api-live/user/room",
            "/node-a/send/download_link",
            "/api/uniqueid/check/",
            "/api/v3/register/user/info/sync/",
            "/api/policy/notice/approve/",
            "/api/private_banner/ack/",
            "/api/privacy/agreement/record/agree/v1",
            "/api/v3/register/verification/age/",
            "/api/register/check/login/name/",
            "/api/user/detail/self/",
            "/passport/web/",
            "/shorten/",
            "/api/seo/kap/product_list/",
            "/bi/notification/reporter/record"
        ],
        "urlRewriteRules": [],
        "sdi": false,
        "region": "sg-tiktok",
        "dev": false,
        "mode": 516,
        "v": false,
        "dfp": false,
        "boe": false,
        "intercept": true
    }
}

jiami2.apply(thisobj,[initobj])

const e = 'https://www.tiktok.com/api/recommend/item_list/?WebIdLastTime=1742619709&aid=1988&app_language=zh-Hans&app_name=tiktok_web&browser_language=zh-CN&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F134.0.0.0%20Safari%2F537.36&channel=tiktok_web&clientABVersions=70508271%2C73184476%2C73294390%2C73294937%2C73340490%2C73343441%2C73399446%2C73408117%2C73408306%2C73411239%2C73419052%2C73425708%2C73433955%2C73439740%2C73449066%2C73449208%2C73459764%2C73470127%2C73479573%2C73482193%2C73495526%2C73501832%2C73518009%2C73536650%2C73551848%2C73560060%2C73568202%2C73569234%2C73569255%2C73570122%2C73575701%2C73590517%2C70405643%2C71057832%2C71200802%2C73004916%2C73171280%2C73208420%2C73385640%2C73574728&cookie_enabled=true&count=12&coverFormat=2&data_collection_enabled=true&device_id=7484494631993427463&device_platform=web_pc&device_type=web_h264&focus_state=false&from_page=fyp&history_len=2&isNonPersonalized=false&is_fullscreen=false&is_page_visible=true&itemID=&language=zh-Hans&odinId=7484494523689108498&os=windows&priority_region=&pullType=2&referer=https%3A%2F%2Fwww.tiktok.com%2F&region=SG&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&screen_height=864&screen_width=1536&showAboutThisAd=true&showAds=false&tz_name=Asia%2FShanghai&user_is_login=false&verifyFp=verify_m8jrj53w_tVQBYr0S_skvm_4lLG_BJrC_QUXFWlWAA0UT&vv_count_fyp=36&watchLiveLastTime=1740643914949&webcast_language=zh-Hans'
const t = {
    "credentials": "include",
    "method": "GET"
};
i = window.fetch.call(null, e, t)
debugger